server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cgv_clone}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET:Y2d2LWNsb25lLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLWFuZC12YWxpZGF0aW9uLW1pbmltdW0tMjU2LWJpdHM}
    token:
      access-expiration-time: 43200000
      refresh-expiration-time: 604800000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

payment:
  mock:
    base-url: https://payment.loopz.co.kr
    api-secret: ${PAYMENT_API_SECRET:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaWxiZXJ0MDkwMzEiLCJjYXRlZ29yeSI6ImFjY2VzcyIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzYxMTMzNTcyLCJleHAiOjI1OTIwMDE3NjExMzM1NzJ9.QdE5KdJTNGZRJoq0uqPgtcNwfgYmflriW_kbx0Yir4ily_dI6z0re_7MA54GmIPLlI1tp2bBEfbfFFlc7hJzpQ}
    store-id: ${PAYMENT_STORE_ID:CEOS-22-3475832}